select count(1) from (


select
a.exchange_type ,
a.stock_code ,
a.stock_type ,
a.internal_code ,
a.frozen_code ,
a.money_type ,
a.stock_name ,
a.spell_code ,
a.relative_code ,
a.stkcode_status ,
a.bond_term ,
a.default_price ,
a.base_price ,
a.last_price ,
a.close_price ,
a.net_value,
a.up_price ,
a.down_price ,
a.high_amount ,
a.low_amount ,
a.trustee ,
a.overdraw ,
a.asset_flag ,
a.amount_per_hand ,
a.store_unit ,
a.report_unit ,
a.buy_unit ,
a.sell_unit ,
a.price_step ,
a.price_grade ,
a.report_direction ,
a.fund_direction ,
a.stock_direction ,
a.fund_frozen ,
a.fund_real_back ,
a.stock_real_back ,
a.match_type ,
a.tn_type ,
a.fund_back_n  ,
a.stock_back_n  ,
a.par_value ,
a.hold_amount ,
a.market_date ,
a.defaultprice_type ,
a.limitprice_type ,
a.baseprice_type ,
a.limit_value_up ,
a.limit_value_low ,
a.buy_client ,
a.sell_client ,
a.buy_holder ,
a.sell_holder ,
a.en_entrust_way ,
a.elig_risk_level ,
a.low_balance ,
a.high_balance ,
a.cancel_low_balance ,
a.cancel_high_balance ,
a.issue_date ,
a.modify_date ,
a.bondinv_flag ,
a.delist_flag ,
a.delist_date ,
a.stbtrans_type ,
nvl(b.sub_stock_type,a.sub_stock_type) as sub_stock_type,
a.stbtrans_status ,
a.stkcode_ctrlstr ,
a.exdividend_flag ,
a.marketmaker_amount ,
a.etl_date from ods_origindb.hs_ods_stkcode a left join (select "A1" as sub_stock_type,stock_code,exchange_type from ods_origindb.hs_ods_stkcode_sub) b on a.exchange_type = b.exchange_type and a.stock_code = b.stock_code order by b.stock_code


) a